/**
 * Downloads the web fonts from Google and writes them into public/fonts/ with a
 * local stylesheet, so the app serves them from its own origin.
 *
 * Why self-host at all: the Google Fonts <link> costs two extra connections
 * (fonts.googleapis.com for the CSS, then fonts.gstatic.com for the files) and
 * the CSS is render-blocking, so nothing paints until both round trips finish.
 * On a throttled mobile connection the fonts then arrived AFTER first paint and
 * the headings reflowed as they swapped in — which is where the 0.595 CLS on
 * the live site came from. Local CLS was 0.003 because the fonts arrived before
 * paint over a fast connection; the bug only shows up on a slow one.
 *
 * font-display: optional is applied on top. It gives the font ~100ms to arrive,
 * and otherwise keeps the fallback for that page load, caching the font for the
 * next one. That makes a font-driven layout shift impossible rather than
 * merely unlikely.
 *
 * Re-run with: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = join(process.cwd(), 'public', 'fonts');
const CSS_OUT = join(process.cwd(), 'src', 'fonts.css');

// Only the families and weights the stylesheets actually ask for.
const FAMILIES = [
  'Inter:wght@400;500;600;700',
  'Sora:wght@600;700;800',
  'Outfit:wght@500;600;700;800',
  'Noto+Sans+Arabic:wght@500;600;700',
];

// Modern Chrome UA, otherwise Google serves the older ttf/woff format.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** Subsets worth shipping. Cyrillic, Greek and Vietnamese are dead weight here. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'arabic']);

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Each @font-face is preceded by a /* subset */ comment.
  const blocks = css.split('/*').slice(1);
  const kept = [];
  let downloaded = 0;

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = /font-family: '([^']+)'/.exec(block)?.[1];
    const weight = /font-weight: (\d+)/.exec(block)?.[1];
    const remote = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    if (!family || !weight || !remote) continue;

    const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
    const bytes = Buffer.from(await (await fetch(remote)).arrayBuffer());
    await writeFile(join(OUT_DIR, file), bytes);
    downloaded += bytes.length;

    const unicodeRange = /unicode-range: ([^;]+);/.exec(block)?.[1];
    kept.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        // See the header comment: this is the guarantee of zero font CLS.
        '  font-display: optional;',
        `  src: url('/fonts/${file}') format('woff2');`,
        unicodeRange ? `  unicode-range: ${unicodeRange};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }

  const header = [
    '/*',
    ' * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' * Self-hosted so the fonts cost no third-party connections, with',
    ' * font-display: optional so a late font can never shift the layout.',
    ' */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}${kept.join('\n\n')}\n`);
  console.log(`${kept.length} faces, ${(downloaded / 1024).toFixed(1)} KB -> public/fonts/`);
}

await main();
